### ISSUE TITLE
Zend-Feed Reader : Not rendering RSS 0.91 throwing an exception

### ISSUE THREAD

**Issue by rajjanorkar** [zendframework/zend-feed#69] opened 2018-03-28 00:00 UTC
Hi Team,

Rendering of this rss feed fails [http://www.brainyquote.com/link/quotefu.rss](http://www.brainyquote.com/link/quotefu.rss)

zend-feed reader throwing and exception.

### Code to reproduce the issue
Use zend feed reader to get the feed entries from  https://www.brainyquote.com/link/quotefu.rss

```
$feed = Zend\Feed\Reader\Reader::import('https://www.brainyquote.com/link/quotefu.rss');
$data = [
    'title'        => $feed->getTitle(),
    'link'         => $feed->getLink(),
    'dateModified' => $feed->getDateModified(),
    'description'  => $feed->getDescription(),
    'language'     => $feed->getLanguage(),
    'entries'      => [],
];
```

### Expected results

Ideally it should not fail as the feed source is in rss 0.91 format.

### Actual results

```
[2018-03-27 00:00:40] production.ERROR: exception 'Zend\Feed\Reader\Exception\InvalidArgumentException' with message 'Invalid XML: Detected use of illegal DOCTYPE' in /home/example/vendor/zendframework/zend-feed/src/Reader/Reader.php:328
Stack trace:
#0 /home/example/vendor/zendframework/zend-feed/src/Reader/Reader.php(266): Zend\Feed\Reader\Reader::importString('<!DOCTYPE rss P...')
Zend\Feed\Reader\Reader::import('https://www.brainyquote.com/link/quotefu.rss')
```

**Comment by froschdesign** [comment] 2018-03-28 08:32
The feed is valid:
https://validator.w3.org/feed/check.cgi?url=https%3A//www.brainyquote.com/link/quotefu.rss

The problem is the `if` construct:

https://github.com/zendframework/zend-feed/blob/54feb89055a9558c1b7bed43b78d5de26fcaf160/src/Reader/Reader.php#L324-L332

We need an unit test for this type of feed.

**Comment by froschdesign** [comment] 2018-03-28 08:33
@rajjanorkar 
Thanks for reporting!

**Comment by rajjanorkar** [comment] 2018-03-28 08:37
@froschdesign  whats the issue? sorry but i did not get it. Please guide me and i will fix it.

**Comment by rajjanorkar** [comment] 2018-03-28 08:40
there is one more use here

https://github.com/zendframework/zend-feed/blob/54feb89055a9558c1b7bed43b78d5de26fcaf160/src/Reader/Reader.php#L442-L450

**Comment by froschdesign** [comment] 2018-03-28 08:51
The XML declaration in the feed is missing, this is the problem and zend-feed checks for this.
Most readers and validators simply ignore the problem of a missing XML declaration. Maybe that's also a solution for this component.

**Comment by rajjanorkar** [comment] 2018-03-28 08:57
ohh okay, thank you. I think it needs some expert intervention like you to fix this issue.

**Comment by froschdesign** [comment] 2018-03-29 06:52
Sorry the labels for this issue are wrong. The current behaviour of zend-feed is correct and the problem is clearly, because a XML documents should begin with a XML declaration.

But it can be an improvement if we accepted / ignore this kind of problem. On the other hand, this opens the door for subsequent errors in parsing and handling of the entire feed.

**Comment by froschdesign** [comment] 2018-03-29 07:06
I will close this issue here, because there are some interesting feature requests still open and accepting this type of error ends up in a mess.

---

Please feel free to add ideas or comments to solve this problem easily or improve the handling!

**Closed as completed by froschdesign** 2018-03-29 07:06 UTC
Labels: invalid

**Comment by froschdesign** [comment] 2019-02-08 07:34
@rajjanorkar 
The XML declaration in the feed is missing but you can add it yourself:

```php
$dom = new DOMDocument();
$dom->load('http://www.brainyquote.com/link/quotefu.rss');
$feed = Zend\Feed\Reader\Reader::importString(
    $dom->saveXML($dom->documentElement) // adds the missing XML declaration
);
```

**Comment by rajjanorkar** [comment] 2019-02-08 11:40
Hi @froschdesign thank you so much for the answer.
i am wondering is there easy way to detect XML declaration is missing or not? Cause those missing XML declaration are very rarer.

**Comment by froschdesign** [comment] 2019-02-08 14:22
@rajjanorkar 
For clarification: a XML document doesn't need a XML declaration, but it _should_ begin with it.
However, to prevent an XXE injection attack, the zend-feed reader checks if a child node of the document is a "document type definition".
Without the XML declaration your feed contains a child node of the type `DOMDocumentType`.
With the XML declaration your feed only contains the child node `rss` which is a `DOMElement`.

 > i am wondering is there easy way to detect XML declaration is missing or not?

Please use the [forum](https://discourse.zendframework.com/) for further questions. Thanks!
