### ISSUE TITLE
Add translate content to utf-8 encoding feature

### ISSUE THREAD

**Issue by rajjanorkar** [zendframework/zend-feed#59] opened 2017-11-12 03:32 UTC
Many feeds are not UTF-8 and so we have issues storing those into DB, before storing we need to translate it to UTF-8, this is not supported in zend-feed.

Can we add feature which will detect the content encoding and translate it to utf-8?

**Comment by froschdesign** [comment] 2017-11-15 14:58
@rajjanorkar 
You have already asked this question: #46

**Comment by rajjanorkar** [comment] 2017-11-15 15:08
@froschdesign sorry i completely forgotten about it.

**Comment by froschdesign** [comment] 2017-12-04 14:41
Duplicate of #46

**Closed as completed by froschdesign** 2017-12-04 14:41 UTC
Labels: duplicate
