### ISSUE TITLE
Not parsing the rss

### ISSUE THREAD

**Issue by rajjanorkar** [zendframework/zend-feed#95] opened 2019-02-08 01:52 UTC
It is not parsing this rss : https://www.brainyquote.com/link/quotefu.rss

i am trying to understand is there bug or it is not supported, anyone please provide some info.

Thank you.

**Comment by froschdesign** [comment] 2019-02-08 06:42
Duplicate of #69

**Closed as completed by froschdesign** 2019-02-08 06:42 UTC
Labels: duplicate
